import Head from "next/head";
import Footer from "../components/Footer";
import MainContainer from "../components/MainContainer";

export default function Home() {
	return (
		<>
			<Head>
				<title>Konrad | Front-End Portfolio</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<MainContainer />
			<Footer />
		</>
	);
}
